---
title: "Elecciones Regionales y Municipales (ERM) 2018 - Análisis de resultados"
author: "Alexander Benites"
subtitle: 'Curso: POL304 - Estadística para el análisis político 2'
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { title: "About", href: "https://github.com/Alexanderbenit7/ERM2018" }
      - { icon: "fa-question-circle", href: "https://google.com", align: right }
      - { icon: "fa-twitter", href: "https://twitter.com/asbenitesa", align: right}
    orientation: columns
    vertical_layout: fill
    
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r include=FALSE}
library(rio)
library(ggplot2)
library(DT)
library(kableExtra)
library(modelsummary)
```

```{r include=FALSE}
data = import("finalData.csv")
mapDIS=sf::read_sf("shapes/Lima.shp") #shapefile
```

```{r include=FALSE}
#Juntamos información con el shape:
mapDIS2=merge(mapDIS,data,by.x='IDDIST',by.y='UBIGEO', all.x = T) #siempre primero el shape
```


# Resultados electorales

Column {data-width=400} {.tabset}
-----------------------------------------------------------------------

### Mapa de resultados ERM 2018

```{r}
mapaleyendaL= ggplot(mapDIS2)+ geom_sf() + theme_light()

mapaleyL= mapaleyendaL + geom_sf(data=mapDIS2,
              aes(fill=GANADOR),color = "gray")
      
mapa1= mapaleyL +
coord_sf() + 
scale_fill_manual(values=c("firebrick","dodgerblue2")) + theme_void() +
  
  
theme(axis.title = element_blank(), axis.text = element_blank(), legend.position = "bottom") + labs(fill=" ") + theme(legend.text = element_text(size = 8)) +
  
labs(title = "Victoria a nivel distrital") +
  
theme(
plot.title = element_text(color="black", size=11, face="bold"))

mapa1
```

### Intensidad del voto (Acción Popular)

```{r}
mapaleyendaL= ggplot(mapDIS2)+ geom_sf() + theme_light()

mapaleyL= mapaleyendaL + geom_sf(data=mapDIS2,
              aes(fill=`ACCION POPULAR`),color = "gray")
      
mapa= mapaleyL +
coord_sf() + 
scale_fill_gradient(low = "seashell",  high = "firebrick", breaks=seq(from=0, to=100, by=20)) + theme_void() + 
  
theme(axis.title = element_blank(), axis.text = element_blank(), legend.position = "right") + labs(fill=" ") + theme(legend.text = element_text(size = 8)) +
  
labs(title = "% de votos válidos por Acción Popular") +
  
theme(
plot.title = element_text(color="black", size=10, face="bold"))

mapa
```

### Intensidad del voto (Podemos)

```{r}
mapaleyendaL= ggplot(mapDIS2)+ geom_sf() + theme_light()

mapaleyL= mapaleyendaL + geom_sf(data=mapDIS2,
              aes(fill=`PODEMOS POR EL PROGRESO DEL PERU`),color = "gray")
      
mapa2= mapaleyL +
coord_sf() + 
scale_fill_gradient(low = "seashell",  high = "dodgerblue2", breaks=seq(from=0, to=100, by=20)) + theme_void() + 
  
theme(axis.title = element_blank(), axis.text = element_blank(), legend.position = "right") + labs(fill=" ") + theme(legend.text = element_text(size = 8)) +
  
labs(title = "% de votos válidos por Podemos") +
  
theme(
plot.title = element_text(color="black", size=10, face="bold"))

mapa2
```


Column {data-width=600}
-----------------------------------------------------------------------

### Tabla de resultados (votos válidos)

```{r include=FALSE}
vote = data[,c(1,15,29)]
```

```{r echo=FALSE}
datatable(vote, filter = "top")
```






# Ausentismo a nivel distrital

Column {data-width=500}
-----------------------------------------------------------------------

### Tabla de resultados (votos válidos)

```{r include=FALSE}
ausen = data[,c(1,13)]
colnames(ausen)[2] = "AUSENTISMO"
```

```{r echo=FALSE}
datatable(ausen, filter = "top")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Ausentismo e IDH

```{r echo=FALSE,message=FALSE,eval=TRUE,fig.show='hold',fig.width=8,fig.height=8}
ggplot(data, aes(x=IDH_2019, y=AUSEN)) + 
  geom_point(size=1.5, shape=23, color="blue") +
  geom_text(label=data$DISTRITO, vjust=-0.5, hjust = 1,color="black", size=3) +
  
      labs(x = "IDH",
       y = "Ausentismo") +

  geom_smooth(method=lm, se=FALSE, linetype="dashed",
             color="darkred") + theme(panel.background = element_blank())
```


# Modelando el voto

```{r include=FALSE}
colnames(data)[15] = "AP"
```

```{r include=FALSE}
data$tDISC = data$DISC_2020/data$POB_2020
data$tMAS80 = data$MAS80_2020/data$POB_2020
```

```{r include=FALSE}
modelo = lm(AP ~ IDH_2019, data = data)
modelo1 = lm(AP ~ IDH_2019 + tDISC + tMAS80, data = data)
modelo2 = lm(AP ~ IDH_2019 + tDISC + tMAS80 + IVA + POBREZA_2019, data = data)
```

Column {data-width=500}
-----------------------------------------------------------------------

### OLS

```{r}
models=list('AP[1]'=modelo,
            'AP[2]'=modelo1,
            'AP[3]'=modelo2)
modelsummary(models, title = "Resultados de todos los modelos",
             stars = TRUE,
             output = "kableExtra")
```



Column {data-width=500}
-----------------------------------------------------------------------

```{r}
cor_g = data[,c("AP","IDH_2019", "tDISC","tMAS80","IVA","POBREZA_2019")]
```

```{r}
library(polycor)
corMatrix=polycor::hetcor(cor_g)$correlations
```

### OLS

```{r}
library(ggcorrplot)
ggcorrplot(corMatrix)
```



